### ISSUE TITLE
Hi, how can I show the count of a certain reaction? I mean, $ article-> reactionSummary () shows an array of all reactions, but I'd like to show the "Like" reaction count

### ISSUE THREAD

**Issue by Marcolino92** [qirolab/laravel-reactions#18]
Hi, how can I show the count of a certain reaction? I mean, $article->reactionSummary() shows an array of all reactions, but I'd like to show the "Like" reaction count

**Comment by hkp22** [comment]
`Reactable` Trait creates `reactions()` relationship method in model. So, you can use this relationship method to count any particular reaction count.

Eg:
```
$article->reactions()->where('type', 'like')->count();
```
