### ISSUE TITLE
Multiple Reactions on Same Model/Reactable

### ISSUE THREAD

**Issue by yespbs** [qirolab/laravel-reactions#19]
I believe the user->reactTo($article, 'like') does not not honor "type" in query in Qirolab\Laravel\Reactions\Traits\Reacts

line 22 which will fail to check multiple reactions on same model and always add/delete the first 

Could you Update ?

**Comment by yespbs** [comment]
Currently I am using same concept but some trait and helpers so need to write a package, just found it as I searched before creating one. This package is awesome and I can send PR

**Comment by hkp22** [comment]
@yespbs  I didn't understand the issue. Sure, you can send PR, and please explain it in detail as well.
