### ISSUE TITLE
Latest version does not differentiate emojis

### ISSUE THREAD

**Issue by devoxis** [qirolab/laravel-reactions#40]
Thanks for the great package. I updated to the latest version 2.6.2, but my reaction summary no longer differentiates between emojis, they are all grouped as the same. In 2.6.0 this worked fine.

**Comment by hkp22** [comment]
The issue isn't clear, so you should explain in detail what you have tried and what error you are getting.

**Comment by devoxis** [comment]
> The issue isn't clear, so you should explain in detail what you have tried and what error you are getting.

This works **$user->reactTo($article, 'like');**
This does not work **$user->reactTo($article, '😊');**

When you do a reaction summary all emojis are grouped together.

**Comment by devoxis** [comment]
Any luck on this in future releases?

**Comment by thijskuilman** [comment]
Same issue here. The "Optimize Reaction Summary" commit is the cause of this issue (commit https://github.com/qirolab/laravel-reactions/commit/04b1fd8a734a123bf1346c6b579a78dd80f5fd2b). If you revert this change, then it works properly again.

**The code that causes the issue (Reactable.php, line 51)**
```
public function reactionSummary()
    {
        if ($this->relationLoaded('reactions')) {
            return $this->reactions->groupBy('type')->map(function ($val) {
                return $val->count();
            });
        }

        return $this->reactions()
            ->groupBy('type')
            ->selectRaw('type, count(id) as total_count')
            ->get()
            ->mapWithKeys(function ($val) {
                return [$val->type => $val->total_count];
            });
    }
```

If you replace the above code with the old code, then it works again:

```
/**
     * Reaction summary.
     *
     * @return \Illuminate\Database\Eloquent\Collection|static[]
     */
    public function reactionSummary()
    {
        return $this->reactions->groupBy('type')->map(function ($val) {
            return $val->count();
        });
    }
```

**Comment by devoxis** [comment]
.
