### ISSUE TITLE
Only `User` can actually use `Reacts`

### ISSUE THREAD

**Issue by rluders** [qirolab/laravel-reactions#44]
Hey folks,

I was looking into the documentation, since I decided to use the package in a project that I'm developing, and well, I found it a little bit weird the fact that I can only use the `Reacts` trait to the `User` model.

For example, in my project I have a `User 1:n Profile` relationship, and well, users can interact with each other contents using more than one Profile, and that means that the `Reacts` should be implemented to the `Profile` and not to the `User`. And, well, I kind of probably assume that it was possible when in the documentation I found `$article->react('like', $user);`.

But... The thing is... how do you folks feel about the possibility to have the `Reacts` to be implemented to any model?

**Comment by hkp22** [comment]
Great Suggestion!
I've implemented your suggestions and released a new version (`v3.0.0`) of this package. Now, you can easily implement `Reacts` for any model.

Here are the steps to get started:
1. Publish the updated Migration files:
```
php artisan vendor:publish --provider="Qirolab\Laravel\Reactions\ReactionsServiceProvider" --tag=migrations
```

2. Publish the Configuration File:
```
php artisan vendor:publish --provider="Qirolab\Laravel\Reactions\ReactionsServiceProvider" --tag="config"
```

In the configuration file, update the value of `reacts_model` like this:
E.g.:
```
'reacts_model' => \App\Models\Profile::class
```
If the value is `null`, it will default to using the `User` Model.

Next, update the value of `reacts_id_column`. This is the column name in the `reactions` table. If the value is `null`, it will default to using `user_id`.
E.g.:
```
'reacts_id_column' => 'profile_id'
```

The rest of the configuration is the same as in the README.md.

---

Also, check out our **[Spec Coder: AI Powered VS Code Extension](https://qirolab.com/spec-coder)** to enhance your coding experience!

[![Spec Coder](https://i.imgur.com/lqkt7a3.png)](https://qirolab.com/spec-coder)
